-- PRITAM KUMAR PORTFOLIO - SUPABASE SCHEMA
-- Copy and paste this into the Supabase SQL Editor to initialize your database.

-- 1. Create Tables

-- Projects Table
CREATE TABLE IF NOT EXISTS public.projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    subtitle TEXT,
    image_url TEXT,
    tags TEXT[],
    link TEXT
);

-- Certificates Table
CREATE TABLE IF NOT EXISTS public.certificates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    title TEXT NOT NULL,
    issuer TEXT,
    year TEXT,
    image_url TEXT
);

-- Timeline Table
CREATE TABLE IF NOT EXISTS public.timeline (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    year TEXT NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    icon_name TEXT
);

-- Services Table
CREATE TABLE IF NOT EXISTS public.services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    icon_name TEXT
);

-- Philosophy Table
CREATE TABLE IF NOT EXISTS public.philosophy (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    icon_name TEXT
);

-- Leads (Contact Form) Table
CREATE TABLE IF NOT EXISTS public.leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    name TEXT NOT NULL,
    contact TEXT NOT NULL,
    description TEXT,
    status TEXT DEFAULT 'new'
);

-- Chat History Table
CREATE TABLE IF NOT EXISTS public.chat_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    role TEXT NOT NULL, -- 'user' or 'assistant'
    content TEXT NOT NULL,
    session_id TEXT
);

-- 2. Storage Setup (Note: Buckets must usually be created via the UI)
-- Create a bucket named 'assets' in the Supabase Dashboard and set it to PUBLIC.

-- 3. Row Level Security (RLS)
-- For a portfolio, we usually want READ access for everyone and WRITE access for the admin.

-- Enable RLS
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.certificates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.timeline ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.philosophy ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_history ENABLE ROW LEVEL SECURITY;

-- Create Public Read Policies
CREATE POLICY "Public Read Projects" ON public.projects FOR SELECT USING (true);
CREATE POLICY "Public Read Certificates" ON public.certificates FOR SELECT USING (true);
CREATE POLICY "Public Read Timeline" ON public.timeline FOR SELECT USING (true);
CREATE POLICY "Public Read Services" ON public.services FOR SELECT USING (true);
CREATE POLICY "Public Read Philosophy" ON public.philosophy FOR SELECT USING (true);

-- Create Public Insert Policy for Leads (so visitors can contact you)
CREATE POLICY "Public Insert Leads" ON public.leads FOR INSERT WITH CHECK (true);

-- 4. Seed Data (Initial Content)
INSERT INTO public.projects (title, subtitle, description, image_url)
VALUES ('AayuVeda AI', 'CEO & Founder', 'An AI system designed to democratize ancient wisdom for modern healthcare.', 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&q=80&w=2070');

INSERT INTO public.timeline (year, title, description)
VALUES ('2023', 'Moved to Gurugram', 'Relocated to the tech hub of India to scale AayuVeda AI and PriMA Tech AI.'),
       ('2024', 'GDG Innovation Symposium', 'Spoke at the Google Developer Group symposium in Gurugram about AI ethics.');

INSERT INTO public.certificates (title, issuer, year, image_url)
VALUES ('IIT Madras BS', 'IIT Madras', '2024', '/pritam_professional.jpg');

INSERT INTO public.philosophy (title, description)
VALUES ('Logic Supremacy', 'Every solution must be rooted in deterministic logic rather than random probability.');

-- Final Policy for Storage (Access for Admin)
-- Run this if you want to allow authenticated uploads via code
-- CREATE POLICY "Allow authenticated uploads" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'assets');
